name: main
on:
  push:
    branches:
      - staging
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: "build"
        run: |
          yarn
          yarn build
      - name: "publish"
        run: |
          npx -p "@getmeli/cli" meli upload ./build \
            --url "https://meli.random.studio" \
            --site "$MELI_SITE" \
            --token "$MELI_TOKEN" \
            --release "$GITHUB_SHA"
        env:
          MELI_SITE: "1c22119b-c7ed-4ead-84e9-7de68a9740e5"
          MELI_TOKEN: ${{ secrets.MELI_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
